id = "pcode-icons"
name = "Pcode Icons Theme"
version = "0.1.0"
schema_version = 1
authors = ["Sanjeev Shrestha <sethstha@gmail.com>"]
description = "Pcode icons theme for Zed"
repository = "https://github.com/sethstha/pcode-icons"
